plugins {
    id 'java'
}

group = 'orangesupport'
version = '1.0'

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
}

repositories {
    mavenCentral()

    ivy {
        url = 'https://github.com/'
        patternLayout {
            artifact '/Anuken/Mindustry/releases/download/v159.7/dependencies.jar'
        }
        metadataSources {
            artifact()
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    compileOnly 'Anuken:Mindustry:v160.5'
}

jar {
    archiveFileName = 'OrangeSupport159.jar'

    // THIS puts the compiled Java classes into the JAR
    from sourceSets.main.output

    // mod.json
    from(rootDir) {
        include 'mod.json'
    }

    // PNG files
    from('assets') {
        into 'assets'
    }
}