plugins {
    id 'java'
}

group = 'orangesupport'
version = '1.0'

repositories {
    mavenCentral()

    ivy {
        url = "https://github.com"
        patternLayout {
            artifact "/Anuken/Mindustry/releases/download/v159.7/dependencies.jar"
        }
        metadataSources {
            artifact()
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
        resources {
            srcDirs = ['src/main/resources', 'assets']
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    compileOnly files("dependencies.jar")
}

jar {
    archiveFileName = "OrangeSupport159.jar"

    // Java .class files
    from sourceSets.main.output

    // mod.json at JAR root
    from(".") {
        include "mod.json"
    }

    // PNG/assets
    from("assets") {
        into "assets"
    }
}